OC.L10N.register(
    "context_agent",
    {
    "API Key HERE" : "API-ключ здесь",
    "Set the API key for the HERE public transport routing" : "Укажите ключ API для маршрутизации публичного транспорта здесь",
    "API key" : "Ключ API",
    "Nextcloud Context Agent" : "Nextcloud контекстный агент",
    "Let Nextcloud assistant take off tasks from your todo list." : "Позвольте помощнику Nextcloud удалять задачи из вашего списка дел.",
    "Let Nextcloud Assistant take off tasks from your todo list. Context Agent provides the AI chat in Assistant with the tools to perform actions in your Nextcloud upon sending instructions in a chat message, for example\n- sending an email\n- writing a message in a Talk room\n- creating calendar entrys\n\nand much more. \n\nThis app needs Nextcloud Assistant and an AI provider to work.\nRead [the documentation](https://docs.nextcloud.com/server/latest/admin_manual/ai/app_context_agent.html).\n\n## Ethical AI Rating\n\n### Rating: 🟢\n\nPositive:\n\n* The software for this app is open source, no trained AI model is used" : "Позвольте помощнику Nextcloud удалять задачи из вашего списка дел. Context Agent предоставляет помощнику AI-чата инструменты для выполнения действий в вашем Nextcloud, например, после отправки инструкций в сообщении чата.\n- отправка электронного письма\n- написание сообщения в комнате обсуждения\n- создание записей в календаре\n\nи многое другое.\n\nДля работы этого приложения требуется Nextcloud Assistant и поставщик искусственного интеллекта.\nПрочитайте [документацию](https://docs.nextcloud.com/server/latest/admin_manual/ai/app_context_agent.html ).\n\n## Этичный Рейтинг искусственного интеллекта\n\n### Рейтинг: 🟢\n\nПоложительный:\n\n* Программное обеспечение для этого приложения имеет открытый исходный код, обученная модель искусственного интеллекта не используется"
},
"nplurals=4; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<12 || n%100>14) ? 1 : n%10==0 || (n%10>=5 && n%10<=9) || (n%100>=11 && n%100<=14)? 2 : 3);");
