OC.L10N.register(
    "context_agent",
    {
    "API Key HERE" : "API кључ HERE",
    "Set the API key for the HERE public transport routing" : "Поставите API кључ за HERE рутирање јавног превоза",
    "API key" : "API кључ",
    "Nextcloud Context Agent" : "Nextcloud Контекст агент",
    "Let Nextcloud assistant take off tasks from your todo list." : "Нека Nextcloud асистент преузме задатке са ваше листе ствари које треба да обавите.",
    "Let Nextcloud Assistant take off tasks from your todo list. Context Agent provides the AI chat in Assistant with the tools to perform actions in your Nextcloud upon sending instructions in a chat message, for example\n- sending an email\n- writing a message in a Talk room\n- creating calendar entrys\n\nand much more. \n\nThis app needs Nextcloud Assistant and an AI provider to work.\nRead [the documentation](https://docs.nextcloud.com/server/latest/admin_manual/ai/app_context_agent.html).\n\n## Ethical AI Rating\n\n### Rating: 🟢\n\nPositive:\n\n* The software for this app is open source, no trained AI model is used" : "Нека Nextcloud Асистент преузме задатке са ваше листе задатака које треба да обавите. Контекст агент омогућава AI чет у асистенту са алатима за извођење акција у вашем Nextcloud облаку након слања инструкција у чет поруци, на пример\n- слање и-мејла\n- писање поруке у Talk соби\n- креирање уноса у календар\n\nи још доста тога. \n\nДа би радила, ова апликација захтева Nextcloud Асистента и пружаоца AI услуге.\nПрочитајте [документацију](https://docs.nextcloud.com/server/latest/admin_manual/ai/app_context_agent.html).\n\n## Етичко рангирање AI\n\n### Ранг: 🟢\n\nПозитивно:\n\n* Софтвер ове апликације је отвореног кода, не користи се ниједан трениран AI модел"
},
"nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);");
